[package]
name = "ll-sparql-parser"
version = "3.5.0"
edition = "2021"
authors = ["Ioannis Nezis <ioannis@nezis.de>"]
description = "A resilient LL parser for SPARQL 1.2"
repository = "https://github.com/IoannisNezis/qlue-ls"
keywords = ["SPARQL", "parser", "rdf"]
license = "MIT"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
indoc = "2.0.5"
insta = "1.48.0"

[dependencies]
logos = "0.16.0"
rowan = "0.17.0"

[build-dependencies]
prettyplease = "0.3.0"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "3.0.0"
ungrammar = "1.16.1"
