[package]
name = "sparql-language-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm"]
wasm = ["dep:wasm-logger"]
native = ["dep:log4rs"]

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
log4rs = { version = "1.3.0", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
indoc = "2.0.5"
nom = "7.1.3"
serde = "1.0.203"
serde_json = "1.0.117"
serde_repr = "0.1.19"
tree-sitter-c2rust = { version = "0.22.6" }
# tree-sitter-sparql = { path = "../tree-sitter-sparql/" }
tree-sitter-sparql = "0.1.3"
wasm-bindgen = "0.2.93"
console_error_panic_hook = { version = "0.1.7", optional = true }
getrandom = { version = "0.2", features = ["js"] }
serde-wasm-bindgen = "0.6.5"
clap = { version = "4.5.16", features = ["derive"] }
camino = "1.1.9"

[build-dependencies]
cc = "1.0.100"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
